import React from "react";

export default class GeneratedCodePanel extends React.Component {
    render() {
        return (
            <div className="generated-code">
                <h3>Generated code</h3>
                <p>The code generated by your actions will be visible here.</p>
            </div>
        );
    }
}